Repository rakenduste-programmeerimine-2022/aegonraha, pull requests merged in 2022-11, with the labels that each got.

#4 Added basic readme contents
  README.md
Labels: enhancement

#19 Folder structure & app skeleton (WF, FE w/ CRA, BE) (related to #2?)
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/.gitkeep
  client/src/index.css
  client/src/index.js
  client/src/pages/.gitkeep
  client/src/reportWebVitals.js
  client/src/setupTests.js
  server/.gitignore
  server/controllers/.gitkeep
  server/index.js
  server/models/.gitkeep
  server/package.json
  server/routes/.gitkeep
  wireframes/.gitkeep
Labels: enhancement, question

#15 Basic stuff(template)
  my-app/.gitignore
  my-app/README.md
  my-app/package-lock.json
  my-app/package.json
  my-app/public/favicon.ico
  my-app/public/index.html
  my-app/public/logo192.png
  my-app/public/logo512.png
  my-app/public/manifest.json
  my-app/public/robots.txt
  my-app/src/App.css
  my-app/src/App.js
  my-app/src/App.test.js
  my-app/src/index.css
  my-app/src/index.js
  my-app/src/logo.svg
  my-app/src/reportWebVitals.js
  my-app/src/setupTests.js
Labels: help wanted

#21 Ran Prettier on the code
  server/package-lock.json
Labels: bug
